local_costmap:
  plugins:
    - {name: obstacle_layer, type: 'costmap_2d::ObstacleLayer'}
    - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}

  global_frame: tb3/odom
  robot_base_frame: tb3/base_footprint

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5  

  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  update_frequency: 2.0
  publish_frequency: 2.0  

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: tb3/base_scan
      topic: /tb3/scan_filtered
      data_type: LaserScan
      marking: true
      clearing: true

  inflation_layer:
    inflation_radius: 0.15

